
<br>
 <div class="containter">
  <div class="row centered-form">
    <div class="col-xs-12 col-sm-6 col-md-4 col-sm-offset-3 col-md-offset-4">

      <div class="panel panel-default">

        <div class="panel-heading">
          <h3 class="panel-title">Please login</h3>
        </div>

        <div class="panel-body">
          <form class="login" action="/home" method="post">

            <div class="form-group">
              <input type="email" name="email" id="email" class="form-control input-sm" placeholder="Email Address">
            </div>

            <div class="form-group">
              <input type="password" name="password_confirmation" id="password_confirmation" class="form-control input-sm" placeholder="Confirm Password">
            </div>

            <input type="submit" value="Login" class="btn btn-success btn-block">

          </form>
          <a href="#">Forget Password</a>
        </div>

      </div>
    </div>
  </div>
